#!/bin/bash

yum update -y
yum install -y docker ecs-init nfs-utils
echo ECS_CLUSTER=%ECS_CLUSTER_NAME% >> /etc/ecs/ecs.config
usermod -a -G docker ec2-user
service docker start
start ecs
docker pull mjs472/wrf-base:0.0.1
mount -o defaults,noatime,bg,soft %NFS_HOST%:/mnt /mnt
echo "ready" > /ready
